name: Frontend CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/frontend
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Cache node modules
              uses: actions/cache@v3
              id: cache-bun
              with:
                  path: ./.node_modules/**
                  key: ${{ runner.os }}-build-${{ hashFiles('./bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build
