name: Frontend CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/frontend
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.npm
                      ${{ github.workspace }}/.next/cache
                      ${{ github.workspace }}/.node_modules
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build
