name: Build and Push Production Container to GHCR

on:
    push:
        branches:
          - main

jobs:
    build-backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/backend
        permissions:
            contents: read

        steps:
          # Step 1: Checkout the code
          - name: Checkout code
            uses: actions/checkout@v3

          # Step 2: Set up GraalVM
          - name: Set up GraalVM
            uses: actions/setup-java@v4
            with:
                distribution: 'graalvm'
                java-version: '21'
                cache: 'gradle'

          # Step 3: Build the Quarkus application
          - name: Build Quarkus application
            run: ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false --no-daemon

          # Step 4: Log in to GitHub Container Registry
          - name: Log in to GHCR
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          # Step 5: Build the container image
          - name: Build Docker image
            run: |
              docker build -f src/main/docker/Dockerfile.native-micro -t ghcr.io/guibi1/sherby-ride-backend:latest .

          # Step 6: Push the container image
          - name: Push Docker image to GHCR
            run: |
              docker push ghcr.io/guibi1/sherby-ride-backend:latest
