name: Build and Push Production Container to GHCR

on:
    push:
        branches:
          - main

jobs:
    build-backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/backend
        permissions:
            contents: read

        steps:
          # Step 1: Checkout the code
          - name: Checkout code
            uses: actions/checkout@v3

          # Step 2: Set up JDK
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '21'
                cache: 'gradle' # Enables Gradle caching

          # Step 3: Cache Gradle dependencies
          - name: Cache Gradle dependencies
            uses: actions/cache@v3
            with:
                path: ~/.gradle/caches
                key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                  gradle-${{ runner.os }}-

          # Step 4: Build the Quarkus application
          - name: Build Quarkus application
            run: ./gradlew build -Dquarkus.package.type=uber-jar --no-daemon

          # Step 5: Log in to GitHub Container Registry
          - name: Log in to GHCR
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          # Step 6: Build the container image
          - name: Build Docker image
            run: |
              docker build -t ghcr.io/${{ github.repository_owner }}/sherby-ride-backend:latest .

          # Step 7: Push the container image
          - name: Push Docker image to GHCR
            run: |
              docker push ghcr.io/${{ github.repository_owner }}/sherby-ride-backend:latest
